#include "class.h"

#undef CONSTRUCTOR_DEFAULT_IMPL
#undef DESTRUCTOR_DEFAULT_IMPL
#undef CD_DEFAULT_IMPL

#undef CONSTRUCTOR_DEFAULT_IMPL_SCOPE
#undef DESTRUCTOR_DEFAULT_IMPL_SCOPE
#undef CD_DEFAULT_IMPL_SCOPE

#undef CONSTRUCTOR_DEFAULT_IMPL_TEMPLATE
#undef DESTRUCTOR_DEFAULT_IMPL_TEMPLATE
#undef CD_DEFAULT_IMPL_TEMPLATE

#undef CONSTRUCTOR_DEFAULT_IMPL_SCOPE_TEMPLATE
#undef DESTRUCTOR_DEFAULT_IMPL_SCOPE_TEMPLATE
#undef CD_DEFAULT_IMPL_SCOPE_TEMPLATE

#undef STATIC

#undef ABSTRACT

#undef HUB

#undef SINGLETON
#undef SINGLETON_IMPL
#undef SINGLETON_IMPL_SCOPE
#undef SINGLETON_IMPL_TEMPLATE
#undef SINGLETON_IMPL_SCOPE_TEMPLATE